using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BinaScraperApp.Services
{
    internal class Maps
    {
        public static readonly Dictionary<string, string> CityMap = new()
        {
            // Şəhərlər və rayonlar
            {"Fərqi Yoxdur", "" },
            { "Ağcabədi","agcabedi" },
            { "Ağdam","agdam" },
            { "Ağdaş","agdas" },
            { "Ağstafa","agstafa" },
            { "Ağsu","agsu" },
            { "Astara","astara" },
            { "Bakı","baki" },
            { "Balakən","balaken" },
            { "Beyləqan","beyleqan" },
            { "Bərdə","berde" },
            { "Biləsuvar","bilesuvar" },
            { "Cəlilabad","celilabad" },
            { "Daşkəsən","dashkesan" },
            { "Gədəbəy","gedebey" },
            { "Gəncə","gence" },
            { "Goranboy","goranboy" },
            { "Göyçay","goycay" },
            { "Göygöl","goygol" },
            { "Hacıqabul","haciqabul" },
            { "Xaçmaz","xacmaz" },
            { "Xırdalan","xirdalan" },
            { "Xızı","xizi" },
            { "Xudat","xudat" },
            { "İmişli","imisli" },
            { "İsmayıllı","ismayilli" },
            { "Kürdəmir","kurdemir" },
            { "Qax","qax" },
            { "Qazax","qazax" },
            { "Qəbələ","qebele" },
            { "Qobustan","qobustan" },
            { "Quba","quba" },
            { "Qusar","qusar" },
            { "Lerik","lerik" },
            { "Lənkəran","lenkeran" },
            { "Masallı","masalli" },
            { "Mingəçevir","mingecevir" },
            { "Naftalan","naftalan" },
            { "Naxçıvan","nakhchivan" },
            { "Naxçıvan MR","naxcivan" },
            { "Neftçala","neftcala" },
            { "Oğuz","oguz" },
            { "Saatlı","saatli" },
            { "Sabirabad","sabirabad" },
            { "Salyan","salyan" },
            { "Samux","samux" },
            { "Siyəzən","siyezen" },
            { "Sumqayıt","sumqayit" },
            { "Şabran","sabran" },
            { "Şamaxı","samaxi" },
            { "Şəki","seki" },
            { "Şəmkir","semkir" },
            { "Şirvan","sirvan" },
            { "Şuşa","susa" },
            { "Tərtər","terter" },
            { "Tovuz","tovuz" },
            { "Ucar","ucar" },
            { "Yardımlı","yardimli" },
            { "Yevlax","yevlax" },
            { "Zaqatala","zaqatala" },
            { "Zərdab","zerdab" },
        };

        public static readonly Dictionary<string, string> LocationMap = new()
        {
            // Metro stansiyaları
            { "20 Yanvar Metro", "5" },
            { "Elmlər Akademiyası Metro", "34" },
            { "İnşaatçılar Metro", "7" },
            { "Nizami Metro", "35" },
            { "28 May Metro", "8" },
            { "Əhmədli Metro", "51" },
            { "Koroğlu Metro", "4" },
            { "Sahil Metro", "38" },
            { "8 Noyabr Metro", "279" },
            { "Gənclik Metro", "2" },
            { "Qara Qarayev Metro", "52" },
            { "Şah İsmayıl Xətai Metro", "36" },
            { "Avtovağzal Metro", "266" },
            { "Həzi Aslanov Metro", "33" },
            { "Memar Əcəmi Metro", "59" },
            { "Ulduz Metro", "3" },
            { "Azadlıq Prospekti Metro", "6" },
            { "Xalqlar Dostluğu Metro", "54" },
            { "Neftçilər Metro", "53" },
            { "Bakmil Metro", "63" },
            { "Xocəsən Metro", "315" },
            { "Nəriman Nərimanov Metro", "1" },
            { "Dərnəgül Metro", "61" },
            { "İçəri Şəhər Metro", "37" },
            { "Nəsimi Metro", "60" },

            // Nişangahlar
            { "Abşeron Ticarət Mərkəzi", "373" },
            { "Dağüstü parkı", "153" },
            { "M.Ə.Sabir parkı", "27" },
            { "Sea Breeze Event Hall", "382" },
            { "Ağ şəhər(Nişangah)", "246" },
            { "DİM", "186" },
            { "M.Hüseynzadə parkı", "137" },
            { "Sevil Qazıyeva parkı", "134" },
            { "Axundov bağı", "30" },
            { "Dostluq kinoteatrı", "176" },
            { "Melissa Park", "364" },
            { "Sədərək \"Elit\"", "367" },
            { "ASAN Xidmət №1", "275" },
            { "Dövlət İdarəçilik Akademiyası", "146" },
            { "Memarlıq və İnşaat Universiteti", "141" },
            { "Sədərk xalça bazarı", "366" },
            { "ASAN Xidmət №2", "276" },
            { "Dövlət Statistika Komitəsi", "170" },
            { "Meyvəli Ticarət Mərkəzi", "374" },
            { "Sədərək şirniyyat bazarı", "368" },
            { "ASAN Xidmət №3", "277" },
            { "Elit Ticarət Mərkəzi", "376" },
            { "Mərkəzi Nəbatat bağı", "157" },
            { "Sədərək tekstil bazarı", "369" },
            { "ASAN Xidmət №5", "278" },
            { "Eurohome Biləcəri Ticarət Mərkəzi", "377" },
            { "Mərkəzi Park", "361" },
            { "Sədərək təsərrüfat bazarı", "370" },
            { "Ayna Sultanova heykəli", "31" },
            { "Fəvvarələr meydanı", "151" },
            { "Mərkəzi Univermaq", "167" },
            { "Sədərək Ticarət Mərkəzi", "371" },
            { "Azadlıq meydanı", "182" },
            { "Filarmoniya bağı", "150" },
            { "Milli Konservatoriya", "161" },
            { "Səməd Vurğun parkı", "28" },
            { "Azərbaycan Dillər Universiteti", "159" },
            { "Grand Hayat Residence", "363" },
            { "Montin bazarı", "132" },
            { "Sirk", "183" },
            { "Azərbaycan Dövlət Neft və Sənaye Universiteti", "139" },
            { "Heydər Əliyev adına İdman Kompleksi", "171" },
            { "Neapol dairəsi", "178" },
            { "Sovetski", "169" },
            { "Azərbaycan kinoteatrı", "173" },
            { "Hüseyn Cavid parkı", "29" },
            { "Neftçi bazası", "187" },
            { "Space TV", "181" },
            { "Azərbaycan turizm institutu", "162" },
            { "Xaqani bağı", "155" },
            { "Nəriman Nərimanov parkı", "26" },
            { "Şəfa stadionu", "185" },
            { "Azneft meydanı", "174" },
            { "Xaqani Ticarət Mərkəzi", "379" },
            { "Nərimanov heykəli", "32" },
            { "Şəhidlər xiyabanı", "184" },
            { "Bakı Asiya Universiteti", "166" },
            { "Xalça Muzeyi", "193" },
            { "Nəsimi bazarı", "189" },
            { "Şəlalə parkı", "147" },
            { "Bakı Dövlət Universiteti", "164" },
            { "İçəri Şeher", "172" },
            { "Nizami kinoteatrı", "175" },
            { "Şərq bazarı", "264" },
            { "Bakı Musiqi Akademiyası", "163" },
            { "İqtisad Universiteti", "143" },
            { "Park Zorge", "133" },
            { "Texniki Universiteti", "140" },
            { "Bakı Slavyan Universiteti", "165" },
            { "İncəsənət və Mədəniyyət Un.", "144" },
            { "Pedaqoji Universiteti", "145" },
            { "Təhsil Nazirliyi", "192" },
            { "Bayıl parkı", "156" },
            { "İzmir parkı", "138" },
            { "Port Baku", "269" },
            { "Tibb Universiteti", "142" },
            { "Beşmərtəbə", "168" },
            { "Keşlə bazarı", "196" },
            { "Prezident parkı", "148" },
            { "Ukrayna dairəsi", "179" },
            { "Binə atçılıq mərkəzi", "317" },
            { "Koala parkı", "25" },
            { "Respublika stadionu", "191" },
            { "Yasamal bazarı", "188" },
            { "Binə Ticarət Mərkəzi", "375" },
            { "Qış parkı", "152" },
            { "Rəssamlıq Akademiyası", "160" },
            { "Zabitlər parkı", "135" },
            { "Cavanşir körpüsü", "180" },
            { "Qurtuluş 93 YK", "384" },
            { "Riyad Ticarət Mərkəzi", "372" },
            { "Zərifə Əliyeva adına park", "158" },
            { "Circus Sea Breeze", "383" },
            { "Laçın Ticarət Mərkəzi", "378" },
            { "Rusiya səfirliyi", "177" },
            { "Zoopark", "136" },
            { "Crescent Bay", "318" },
            { "Landau Məktəbi (Sea Breeze)", "381" },
            { "Sahil bağı", "154" },

            // Rayonlar
            { "Aşağı Güzdək", "316" },
            { "Atyalı", "362" },
            { "Ceyranbatan", "258" },
            { "Çiçək", "65" },
            { "Digah", "263" },
            { "Fatmayı", "116" },
            { "Görədil", "194" },
            { "Güzdək", "365" },
            { "Hökməli", "50" },
            { "Köhnə Corat", "115" },
            { "Qobu", "261" },
            { "Masazır", "198" },
            { "Mehdiabad", "112" },
            { "Məmmədli", "265" },
            { "Novxanı", "113" },
            { "Pirəkəşkül", "241" },
            { "Saray", "111" },
            { "Yeni Corat", "114" },
            { "Zuğulba", "106" },
            { "Abşeron(Ümumi Rayon)", "197" },
            { "2-ci Alatava", "73" },
            { "28 May", "259" },
            { "6-cı mikrorayon", "128" },
            { "7-ci mikrorayon", "129" },
            { "8-ci mikrorayon", "130" },
            { "9-cu mikrorayon", "131" },
            { "Biləcəri", "17" },
            { "Binəqədi", "18" },
            { "Xocəsən", "9" },
            { "Xutor", "104" },
            { "M.Ə.Rəsulzadə", "19" },
            { "Sulutəpə", "64" },
            { "Binəqədi(Ümumi Rayon)", "58" },
            { "Ələt", "24" },
            { "Qızıldaş", "257" },
            { "Qobustan", "45" },
            { "Lökbatan", "20" },
            { "Müşfiqabad", "98" },
            { "Puta", "22" },
            { "Sahil", "21" },
            { "Səngəçal", "23" },
            { "Şubanı", "71" },
            { "Qaradağ(Ümumi Rayon)", "57" },
            { "Ağ şəhər", "314" },
            { "Əhmədli", "100" },
            { "Həzi Aslanov", "99" },
            { "Köhnə Günəşli", "200" },
            { "NZS", "233" },
            { "Xətai(Ümumi Rayon)", "16" },
            { "1-ci mikrorayon", "123" },
            { "2-ci mikrorayon", "124" },
            { "3-cü mikrorayon", "125" },
            { "4-cü mikrorayon", "126" },
            { "5-ci mikrorayon", "127" },
            { "Kubinka", "70" },
            { "Nəsimi(Ümumi Rayon)", "190" },
            { "Böyükşor", "68" },
            { "Nərimanov(Ümumi Rayon)", "10" },
            { "8-ci kilometr", "74" },
            { "Keşlə", "105" },
            { "Nizami(Ümumi Rayon)", "11" },
            { "Pirallahı(Ümumi Rayon)", "249" },
            { "Albalılıq", "313" },
            { "Bakıxanov", "69" },
            { "Balaxanı", "243" },
            { "Bilgəh", "118" },
            { "Kürdəxanı", "120" },
            { "Maştağa", "122" },
            { "Nardaran", "119" },
            { "Pirşağı", "121" },
            { "Ramana", "76" },
            { "Sabunçu", "86" },
            { "Savalan", "234" },
            { "Sea Breeze", "380" },
            { "Yeni Balaxanı", "242" },
            { "Yeni Ramana", "77" },
            { "Zabrat", "78" },
            { "Sabunçu(Ümumi Rayon)", "13" },
            { "20-ci sahə", "48" },
            { "Badamdar", "46" },
            { "Bayıl", "49" },
            { "Bibiheybət", "47" },
            { "Şıxov", "260" },
            { "Səbail(Ümumi Rayon)", "12" },
            { "Bahar", "256" },
            { "Bülbülə", "244" },
            { "Dədə Qorqud", "255" },
            { "Əmircan", "72" },
            { "Günəşli", "91" },
            { "Hövsan", "93" },
            { "Qaraçuxur", "75" },
            { "Massiv A", "81" },
            { "Massiv B", "82" },
            { "Massiv D", "85" },
            { "Massiv G", "84" },
            { "Massiv V", "83" },
            { "Suraxanı", "87" },
            { "Şərq", "80" },
            { "Yeni Günəşli", "92" },
            { "Yeni Suraxanı", "88" },
            { "Zığ", "89" },
            { "Suraxanı(Ümumi Rayon)", "14" },
            { "Yasamal", "103" },
            { "Yeni Yasamal", "102" },
            { "Yasamal(Ümumi Rayon)", "56" },
            { "Binə", "79" },
            { "Buzovna", "117" },
            { "Dübəndi", "97" },
            { "Gürgən", "252" },
            { "Qala", "95" },
            { "Mərdəkan", "109" },
            { "Şağan", "108" },
            { "Şimal DRES", "107" },
            { "Şüvəlan", "110" },
            { "Türkan", "94" },
            { "Zirə", "96" },
            { "Xəzər(Ümumi Rayon)", "15" }
        };

        public static readonly Dictionary<string, string> PropertyMap = new()
        {
            { "Mənzil", "menziller" },
            { "Həyət evi/Bağ evi", "heyet-evleri" },
            { "Ofis", "ofisler" },
            { "Qaraj", "qarajlar" },
            { "Torpaq", "torpaq" },
            { "Obyekt", "obyektler" }
        };

        public static readonly Dictionary<string, string> BuildingMap = new()
        {
            { "Fərqi yoxdur", "" },
            { "Yeni tikili", "yeni-tikili" },
            { "Köhnə tikili", "kohne-tikili" },
        };

        public static readonly Dictionary<string, string> RepairMap = new()
        {
            { "Fərqi yoxdur", "" },
            { "Təmirlidir", "&has_repair=true" },
            { "Təmirsiz", "&has_repair=false" },
        };

        public static readonly Dictionary<string, string> RoomMap = new()
        {
            { "1", "1" },
            { "2", "2" },
            { "3", "3" },
            { "4", "4" },
            { "5+", "5%2B" }
        };
    }
}
